#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul  9 23:18:32 2018

@author: gabriel
"""

# Testcase 1 

t1 = S.Task(20,100)
t1.pltColor = 'red'
t2 = S.Task(40,150)
t2.pltColor = 'green'
t3 = S.Task(100,350)
t3.pltColor = 'blue'
tasks = [t1, t2, t3]
RM = S.rateMonotonic(tasks)
scheduler = S.Scheduler(RM)

